name: Build and Release

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Package artifacts
        run: dotnet publish -c Release --no-build --output ./publish

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          majer_patter: "major:"
          minor_patter: "feat:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: version

      - name: Create and push new tag
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          git tag v$NEW_VERSION
          git push origin v$NEW_VERSION

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          NEW_VERSION: ${{ steps.version.outputs.version }}
        with:
          tag_name: vNEW_VERSION
          release_name: Release NEW_VERSION
          draft: false
          prerelease: false

      - name: ZIP File
        run: zip -r uEssentials.zip ./publish

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uEssentials.zip
          asset_name: uEssentials.zip
          asset_content_type: application/zip
